name: PR Check
on: [pull_request]
jobs:
  test:
    runs-on: self-hosted
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v3
      - name: python setup
        run: |
          pip install poetry==1.4.2
          python3 -m poetry install --with dev
      - name:  format check 
        run: make format-check
      - name: dependency check
        run: make dep-check
      - name: pytest
        run: make test
      - name: upload test results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov/
      
      
      
    
